notifications:
  email: false

sudo: false

os:
- linux

language: node_js

node_js:
- 8

addons:
  apt:
    packages:
      - libsecret-1-dev

script:
- npm run vscode:prepublish

before_deploy:
- npm install -g vsce
- vsce package

deploy:
  provider: releases
    api_key:
      secure: Pf/FD9fwLip11OH4LTp5+i3QBFLffcTFqF9sVrDJIjWi5fiR3Q2U05oWwMwto2QMMSflnEIsbBupXqnG36aFJmk+IrJ2cZXUXeUgo9yNqu/ZmVq7/hj0vLQ916ZaFHNefT1REkqXgSnxa6BF1yttN3T6cC2W8irHDhWUy8C4DFNMHcrQbu8kF30PeqJi8vahDk6OWVMjUzc8HZbpo/lzwfqLMxAY7Y9RlbBYzUnLz+yAs99ZOuZKS1K71f/Ti/v9qO5hhlSqj9pg1cEfyDc05+uh4SOEUfRCikjBN2dO5wqIykWWdEv64I43siXsEh69Sc/bxSHQeAgt3bPAJC5pJWX5S5mQjEq5M3bv6lLVH/sY5L8T2QijzcvQ1hG5Tc10jcV5oK91D+yYKSjaJZYjvW2T27eJoEAXT5TZF4MbAMBqCpI+iyBWWeHMLJaFMe7rODTJzvnQm47RAWI1VQY/M37vpob0IQiTNALhJnMREMd/MHazNRJcZeeuI1nUqlKWoXyyLoCcF96uH8BifGCKmwO2qaFT6vps1xlZcOmZblgYvckaEVTLxpURh3EIPWL9zaVubYo3nOOyB5/JrOlseYPoG4Uu7AsWImLJ/YAqBmT27PmGcFMl2YcwYT2tl0P/LPr7LoP0fklXZ5ui01IoMnZ+QKCMnwr8vSjkjg3u0U8=
    file: feeluown-remote*.vsix
    skip_cleanup: true
    on:
      tags: true
